server.port: 8090
server.servlet.context-path: /api

debug: false
logging.level:
  root: INFO
  org.springframework.jdbc.core: DEBUG
  com.topcoder.productsearch: DEBUG
  com.topcoder.productsearch.crawler.core.Scheduler: INFO

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/website_crawler?useSSL=false&nullNamePatternMatchesAll=true
    username: root
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 60000
  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
      base-path: /
      path-mapping:
        health: healthcheck

server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

cors:
  allowed-origins: "*"
  allowed-methods: HEAD,GET,PUT,POST,DELETE

crawler-settings:
  request-interval-mills: 1000
  site-time-limit-seconds: 60
  page-download-timeout-minutes: 1
  page-download-max-retry: 5
  max-crawl-depth: 10
  download-pool-size: 100
  download-queue-size: 1024
  response-process-pool-size: 10

